nakjun12/Gyul_Box

oneroom/src/main/java/jeju/oneroom/coordinate/entity/Coordinate.java
oneroom/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
oneroom/src/main/java/jeju/oneroom/review/entity/Review.java
oneroom/src/main/java/jeju/oneroom/si/entity/Si.java
oneroom/src/main/java/jeju/oneroom/town/entity/Town.java

- [#2]
- Si, Town, HouseInfo, Review 엔티티 생성 및 연관관계 설정
- Coordinate 엔티티 생성을 통해 코드 가독성 향상

feat - #2 : Si, Town, Houseinfo, Review, Coordinate 엔티티 생성

---

oneroom/build.gradle
oneroom/src/main/java/jeju/oneroom/Post/entitiy/Post.java
oneroom/src/main/java/jeju/oneroom/message/entity/Message.java
oneroom/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
oneroom/src/main/java/jeju/oneroom/user/controller/UserController.java
oneroom/src/main/java/jeju/oneroom/user/entity/User.java
oneroom/src/main/resources/application.yml

- [#2]
- user, post, postComment, message 엔티티 생성 및 연관관계 설정

feat - #2 : user, post, postComment, message 엔티티 생성

---

oneroom/build.gradle
oneroom/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
oneroom/src/main/java/jeju/oneroom/review/entity/Review.java
oneroom/src/main/java/jeju/oneroom/si/entity/Si.java
oneroom/src/main/java/jeju/oneroom/town/entity/Town.java

- [#2 ]
- createdAt, modifiedAt 변수명 통일을 위한 수정

fix - #2 : createAt, modifiedAt 변수명 수정

---

oneroom/src/main/java/jeju/oneroom/common/entity/Coordinate.java
oneroom/src/main/java/jeju/oneroom/common/entity/Rate.java
oneroom/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
oneroom/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
oneroom/src/main/java/jeju/oneroom/message/entity/Message.java
oneroom/src/main/java/jeju/oneroom/review/controller/ReviewController.java
oneroom/src/main/java/jeju/oneroom/review/entity/Review.java
oneroom/src/main/java/jeju/oneroom/si/controller/SiController.java
oneroom/src/main/java/jeju/oneroom/si/entity/Si.java
oneroom/src/main/java/jeju/oneroom/town/controller/TownController.java
oneroom/src/main/java/jeju/oneroom/town/entity/Town.java
oneroom/src/main/java/jeju/oneroom/user/entity/User.java

- [#9 ]
- Si, Town, HouseInfo, Review 컨트롤러 생성
- Rate 임베디드 타입 생성 후 HouseInfo와 Review에 추가

feat - #9 : Si, Town, Houseinfo, Review Controller 생성

---

server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
server/src/main/java/jeju/oneroom/review/entity/Review.java
server/src/main/java/jeju/oneroom/si/dto/SiDto.java
server/src/main/java/jeju/oneroom/town/dto/TownDto.java

- [#10  ]
- Si, Town, HouseInfo, Review Dto 생성
- HouseInfo에 대한 get 요청 시 review도 함께 전동
- 리뷰에 좋아요 기능 추가
- 리뷰 Controller에 최신 순 5개, 추천 순 5개에 대한 get 요청 삭제(Post Controller로 이동)

[BE] feat - #10 : Si, Town, Houseinfo, Review Dto 생성

---

server/src/main/java/jeju/oneroom/Post/controller/PostController.java
server/src/main/java/jeju/oneroom/Post/dto/PostDto.java
server/src/main/java/jeju/oneroom/Post/entitiy/Post.java
server/src/main/java/jeju/oneroom/message/controller/MessageController.java
server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
server/src/main/java/jeju/oneroom/postComment/controller/PostCommentController.java
server/src/main/java/jeju/oneroom/postComment/dto/PostCommentDto.java
server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
server/src/main/java/jeju/oneroom/user/controller/UserController.java
server/src/main/java/jeju/oneroom/user/dto/UserDto.java
server/src/main/java/jeju/oneroom/user/entity/User.java

- [#10  ]
- User, Message, Post, PostComment Dto 생성
- HouseInfo - Post 연관관계 삭제
- PostController에 최신 순 5개, 추천 순 5개에 대한 get 요청 추가
- MessageController에 userId로 받은 모든 메시지 가져오는 api 추가
- PostController에 user-id로 유저 검색 후 유저가 작성한 글 가져오는 api 추가

[BE] feat - #10 : post, postComment, message, user controller DTO 1차 생성

---

server/src/main/java/jeju/oneroom/Post/entitiy/Post.java
server/src/main/java/jeju/oneroom/Post/repository/PostRepository.java
server/src/main/java/jeju/oneroom/message/entity/Message.java
server/src/main/java/jeju/oneroom/message/repository/MessageRepository.java
server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
server/src/main/java/jeju/oneroom/postComment/repository/PostCommentRepository.java
server/src/main/java/jeju/oneroom/user/entity/User.java
server/src/main/java/jeju/oneroom/user/repository/UserRepository.java
server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
server/src/test/java/jeju/oneroom/message/entity/MessageTest.java
server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
server/src/test/java/jeju/oneroom/user/entity/UserTest.java

- [#30  ]
- User, Message, Post, PostComment 엔티티 생성  테스트 구현
- USER -> USERS 테이블명 변경
- entity에 빌더패턴 적용
- 각 레포지토리 생성

[BE] feat - #30 : post, postComment, message, user 엔티티 생성 단위 테스트

---

client/src/component/organisms/Header/header.tsx
client/src/pages/_app.tsx
client/src/pages/atoms/index.tsx
client/src/pages/home.module.scss

[FE] -> [Client] header, footer 배치 완

[FE] -> [Client] header, footer 배치 완

---

server/build.gradle
server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
server/src/main/java/jeju/oneroom/si/controller/SiController.java
server/src/main/java/jeju/oneroom/si/dto/SiDto.java
server/src/main/java/jeju/oneroom/si/entity/Si.java
server/src/main/java/jeju/oneroom/si/mapper/SiMapper.java
server/src/main/java/jeju/oneroom/town/controller/TownController.java
server/src/main/java/jeju/oneroom/town/dto/TownDto.java
server/src/main/java/jeju/oneroom/town/mapper/TownMapper.java
server/src/main/resources/application.yml
server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java

- [#35]
-  Si, Town, Houseinfo, Review Mapper 생성
- build.gradle 수정 ( lombook과 mapstruct 충동 해결, security 주석처리)
- 각 컨트롤러의 get(단건조회) 메서드 수정

[BE] feat - #35 : Si, Town, Houseinfo, Review mapper 생

---

server/build.gradle
server/src/main/java/jeju/oneroom/Post/controller/PostController.java
server/src/main/java/jeju/oneroom/Post/dto/PostDto.java
server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
server/src/main/java/jeju/oneroom/postComment/controller/PostCommentController.java
server/src/main/java/jeju/oneroom/postComment/dto/PostCommentDto.java
server/src/main/java/jeju/oneroom/user/controller/UserController.java
server/src/main/java/jeju/oneroom/user/dto/UserDto.java
server/src/main/resources/application.yml
server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
server/src/test/java/jeju/oneroom/user/entity/UserTest.java

- [#35  ]
- User, Message, Post, PostComment mapstruct 구현
- dto별 @Getter @AllArgsConstructor @Builder @NoArgsConstructor 작성
- getMapping 컨트롤러 테스트 위해 구현
- postResponseDto에 writer 추가

[BE] feat - #35 : post, postComment, message, user mapper 구현

---

server/src/main/java/jeju/oneroom/common/dto/ListResponseDto.java
server/src/main/java/jeju/oneroom/common/dto/MultiResponseDto.java
server/src/main/java/jeju/oneroom/common/dto/PageInfo.java
server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
server/src/main/java/jeju/oneroom/si/controller/SiController.java
server/src/main/java/jeju/oneroom/si/mapper/SiMapper.java
server/src/main/java/jeju/oneroom/town/controller/TownController.java
server/src/main/java/jeju/oneroom/town/mapper/TownMapper.java
server/src/main/java/jeju/oneroom/town/repository/TownRepository.java
server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
server/src/test/java/jeju/oneroom/town/entity/TownTest.java

- [#35]
-  Si, Town, Houseinfo, Review Mapper 수정
- MultiresponseDto, ListResponseDto, PageInfo 생성

[BE] feat - #35 : Si, Town, Houseinfo, Review mapper 수정 및 commen 생성

---

client/src/pages/index.tsx

[FE -> Client] 메인페이지 게시글 작성 완

---

server/src/main/java/jeju/oneroom/Post/controller/PostController.java
server/src/main/java/jeju/oneroom/Post/mapper/PostMapper.java
server/src/main/java/jeju/oneroom/Post/repository/PostRepository.java
server/src/main/java/jeju/oneroom/message/controller/MessageController.java
server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
server/src/main/java/jeju/oneroom/message/mapper/MessageMapper.java
server/src/main/java/jeju/oneroom/message/repository/MessageRepository.java
server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
server/src/main/java/jeju/oneroom/postComment/mapper/PostCommentMapper.java
server/src/test/java/jeju/oneroom/message/entity/MessageTest.java
server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java

- [#11]
-  postComment와 user manytoOne 단방향 매핑 구현
- 연관관계 매핑에 따른 postComment test 코드 수정
- api문서화를 위한 getMapping 컨트롤러 구현

[BE] feat - #11 : post, postComment, message, user api 문서화를 위한 구현

---

server/src/main/java/jeju/oneroom/message/service/MessageService.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
server/src/main/java/jeju/oneroom/review/service/ReviewService.java
server/src/main/java/jeju/oneroom/user/service/UserService.java

- [#66]
-  User, Review, Message Service 계층 1차 구현
- ReviewController에 최신순 추천순 로직 구현

[BE] feat - #66 : Service 계층 1차 구현 및 ReviewController에 최신순 추천순 로직 구현

---

server/src/test/java/jeju/oneroom/OneroomApplicationTests.java
server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
server/src/test/java/jeju/oneroom/user/entity/UserTest.java

[BE] TestCode 복구

---

server/src/main/java/jeju/oneroom/area/controller/AreaController.java
server/src/main/java/jeju/oneroom/area/dto/AreaDto.java
server/src/main/java/jeju/oneroom/area/entity/Area.java
server/src/main/java/jeju/oneroom/area/service/AreaService.java
server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
server/src/test/java/jeju/oneroom/user/entity/UserTest.java

- [#66]
-  HouseInfo, Area Service 계층 1차 구현
- Town, Si 엔티티 제거 후 Area로 통합 및 메서드명 수정
- HouseInfo Controller의 findAreaHouseInfos 메서드 Level에 따른 로직 수정

[BE] feat - #66 : Area, HouseInfo Service 1차 구현

---

server/src/main/java/jeju/oneroom/area/controller/AreaController.java
server/src/main/java/jeju/oneroom/area/entity/Area.java
server/src/main/java/jeju/oneroom/area/service/AreaService.java
server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
server/src/test/java/jeju/oneroom/area/entity/AreaTest.java

- [#67]
-  Area, HouseInfo Controller 계층 2차 구현
-  Area, HouseInfo Service 계층 수정
- Area의 컬럼명 toen_id -> area_id로 수정

[BE] feat - #67 : Area, HouseInfo Controller 2차 구현

---

server/src/main/java/jeju/oneroom/message/controller/MessageController.java
server/src/main/java/jeju/oneroom/user/controller/UserController.java
server/src/main/java/jeju/oneroom/user/dto/UserDto.java
server/src/main/java/jeju/oneroom/user/entity/User.java
server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
server/src/main/java/jeju/oneroom/user/service/UserService.java
server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
server/src/test/java/jeju/oneroom/user/entity/UserTest.java

-  UserDto.Patch 수정
- ReviewTest 수정

[BE] UserDto.Patch 수정 및 ReviewTest 수정

---

server/src/main/java/jeju/oneroom/area/controller/AreaController.java
server/src/main/java/jeju/oneroom/area/repository/AreaRepository.java
server/src/main/java/jeju/oneroom/area/service/AreaService.java
server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
server/src/main/java/jeju/oneroom/message/entity/Message.java
server/src/main/java/jeju/oneroom/post/entitiy/Post.java
server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
server/src/main/java/jeju/oneroom/review/entity/Review.java
server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
server/src/main/java/jeju/oneroom/review/service/ReviewService.java
server/src/main/java/jeju/oneroom/reviewLike/controller/ReviewLikeController.java
server/src/main/java/jeju/oneroom/reviewLike/entity/ReviewLike.java
server/src/main/java/jeju/oneroom/reviewLike/repository/ReviewLikeRepository.java
server/src/main/java/jeju/oneroom/reviewLike/service/ReviewLikeService.java
server/src/main/java/jeju/oneroom/user/controller/UserController.java
server/src/main/java/jeju/oneroom/user/entity/User.java
server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
server/src/main/java/jeju/oneroom/user/service/UserService.java
server/src/main/resources/application.yml
server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java

- [#68]
-  HouseInfo, Review, ReviewLikes Service 2차 구현
- Area 시, 동, 면, 읍 이름을 통한 조회 추가
- Service단의 Service, Repository 의존 수정 및 리팩토링
- HouseInfoDto.SimpleResponse의 위도 경도 삭제
- @Fomula를 통한 Count 변수 성능 최적화
- Review의 주소를 통한 HouseInfo 매핑 추가
- Verified매서드 추가
- GeneratedValue Identity 추가
- 엔티티의 update 및 setproperties 매서드 추가
- 리뷰 추천 엔티티, 서비스, 컨크롤러, 레보지토리 생성 및 매핑

[BE] feat - #68 : HouseInfo, Review, ReviewLikes Service 2차 구현

---

server/src/main/java/jeju/oneroom/area/controller/AreaController.java
server/src/main/java/jeju/oneroom/common/entity/Rate.java
server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
server/src/main/java/jeju/oneroom/review/service/ReviewService.java
server/src/test/java/jeju/oneroom/area/service/AreaServiceTest.java

- [#69]
- Area 검색 API 변경
- Rate 디폴트 값 설정 및 avgRate 로직 수정
- 건물 주소를 통한 HouseInfo 검색 추가
- 추가된 검색에 대한 ResponseDto 생성
- 리뷰 추가에 따른 건물 정보의 별점 수정 로직 생성
- Review 와 HouseInfo의 매핑 매개변수 Address에서 HouseInfo로 변경

[BE] feat - #69 : Area, HouseInfo, Review, ReviewLikes Service 단위 테스트를 위한 비즈니스 로직 점검

---

server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
server/src/test/java/jeju/oneroom/area/service/AreaServiceTest.java
server/src/test/java/jeju/oneroom/houseInfo/service/HouseInfoServiceTest.java

- [#69]
- Area Service 단위 테스트 제작 완료
- HouseInfo Service 단위 테스트 일부 제작

[BE] feat - #69 : HouseInfo, Area Service계층 단위 테스트 일시적 중단

---

server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
server/src/main/java/jeju/oneroom/user/dto/UserDto.java
server/src/main/java/jeju/oneroom/user/service/UserService.java
server/src/main/java/jeju/oneroom/validation/RateValidator.java
server/src/main/java/jeju/oneroom/validation/ValidRate.java
server/src/test/java/jeju/oneroom/houseInfo/service/HouseInfoServiceTest.java

- [#113]
- avgRate 필드 타입 Double로 변경
- User PostDto 삭제
- Review, User Dto 유효성 검증 어노테이션 추가
- Rate 객체 유효성 검증 커스텀 어노테이션 생성
- Controller 단 유효성 검증 어노테이션 추가
- HouseInfroServiceTest 일부 수정

[BE] feat - #113 : Dto 필드 유효성 검증 추가

---

server/src/main/java/jeju/oneroom/post/repository/PostCustomRepository.java
server/src/main/java/jeju/oneroom/post/repository/PostCustomRepositoryImpl.java
server/src/main/java/jeju/oneroom/post/repository/PostRepository.java
server/src/main/java/jeju/oneroom/post/service/PostService.java
server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentCustomRepository.java
server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentCustomRepositoryImpl.java
server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentRepository.java
server/src/main/java/jeju/oneroom/postcomment/service/PostCommentService.java

- [#121]
- Post Repository querydsl 적용
- PostComment Repository querydsl 적용

[BE] feat - #121: Post, PostComment repository querydsl 적용

---

server/src/main/java/jeju/oneroom/exception/ExceptionCode.java
server/src/main/java/jeju/oneroom/exception/GlobalExceptionAdvice.java
server/src/main/java/jeju/oneroom/post/controller/PostController.java
server/src/main/java/jeju/oneroom/post/dto/PostDto.java
server/src/main/java/jeju/oneroom/post/entity/Post.java
server/src/main/java/jeju/oneroom/post/service/PostService.java
server/src/main/java/jeju/oneroom/postcomment/controller/PostCommentController.java
server/src/main/java/jeju/oneroom/postcomment/dto/PostCommentDto.java
server/src/main/java/jeju/oneroom/postcomment/entity/PostComment.java
server/src/main/java/jeju/oneroom/postcomment/service/PostCommentService.java
server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
server/src/main/java/jeju/oneroom/review/entity/Review.java
server/src/main/java/jeju/oneroom/review/service/ReviewService.java

- [#124]
- Post, PostComment, Review 수정 및 삭제 시, 동일 유저 검증 로직 추가

[BE] feat - #124: Post, PostComment, Review 도메인 동일 유저 로직 추가
